/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicGoRouteImport } from './routes/api/public/go'
import { Route as ApiPublicDiscordCallbackRouteImport } from './routes/api/public/discord/callback'
import { Route as ApiPublicDiscordLoginRouteImport } from './routes/api/public/discord/login'
import { Route as ApiPublicDiscordLogoutRouteImport } from './routes/api/public/discord/logout'
import { Route as ApiPublicRobloxCheckRouteImport } from './routes/api/public/roblox/check'
import { Route as ApiPublicRobloxJoinRouteImport } from './routes/api/public/roblox/join'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoRoute = ApiPublicGoRouteImport.update({
  id: '/api/public/go',
  path: '/api/public/go',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordCallbackRoute =
  ApiPublicDiscordCallbackRouteImport.update({
    id: '/api/public/discord/callback',
    path: '/api/public/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscordLoginRoute = ApiPublicDiscordLoginRouteImport.update({
  id: '/api/public/discord/login',
  path: '/api/public/discord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordLogoutRoute = ApiPublicDiscordLogoutRouteImport.update({
  id: '/api/public/discord/logout',
  path: '/api/public/discord/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobloxCheckRoute = ApiPublicRobloxCheckRouteImport.update({
  id: '/api/public/roblox/check',
  path: '/api/public/roblox/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobloxJoinRoute = ApiPublicRobloxJoinRouteImport.update({
  id: '/api/public/roblox/join',
  path: '/api/public/roblox/join',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/go': typeof ApiPublicGoRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
  '/api/public/discord/logout': typeof ApiPublicDiscordLogoutRoute
  '/api/public/roblox/check': typeof ApiPublicRobloxCheckRoute
  '/api/public/roblox/join': typeof ApiPublicRobloxJoinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/go': typeof ApiPublicGoRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
  '/api/public/discord/logout': typeof ApiPublicDiscordLogoutRoute
  '/api/public/roblox/check': typeof ApiPublicRobloxCheckRoute
  '/api/public/roblox/join': typeof ApiPublicRobloxJoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/go': typeof ApiPublicGoRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
  '/api/public/discord/logout': typeof ApiPublicDiscordLogoutRoute
  '/api/public/roblox/check': typeof ApiPublicRobloxCheckRoute
  '/api/public/roblox/join': typeof ApiPublicRobloxJoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/go'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
    | '/api/public/discord/logout'
    | '/api/public/roblox/check'
    | '/api/public/roblox/join'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/go'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
    | '/api/public/discord/logout'
    | '/api/public/roblox/check'
    | '/api/public/roblox/join'
  id:
    | '__root__'
    | '/'
    | '/api/public/go'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
    | '/api/public/discord/logout'
    | '/api/public/roblox/check'
    | '/api/public/roblox/join'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicGoRoute: typeof ApiPublicGoRoute
  ApiPublicDiscordCallbackRoute: typeof ApiPublicDiscordCallbackRoute
  ApiPublicDiscordLoginRoute: typeof ApiPublicDiscordLoginRoute
  ApiPublicDiscordLogoutRoute: typeof ApiPublicDiscordLogoutRoute
  ApiPublicRobloxCheckRoute: typeof ApiPublicRobloxCheckRoute
  ApiPublicRobloxJoinRoute: typeof ApiPublicRobloxJoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/go': {
      id: '/api/public/go'
      path: '/api/public/go'
      fullPath: '/api/public/go'
      preLoaderRoute: typeof ApiPublicGoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/callback': {
      id: '/api/public/discord/callback'
      path: '/api/public/discord/callback'
      fullPath: '/api/public/discord/callback'
      preLoaderRoute: typeof ApiPublicDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/login': {
      id: '/api/public/discord/login'
      path: '/api/public/discord/login'
      fullPath: '/api/public/discord/login'
      preLoaderRoute: typeof ApiPublicDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/logout': {
      id: '/api/public/discord/logout'
      path: '/api/public/discord/logout'
      fullPath: '/api/public/discord/logout'
      preLoaderRoute: typeof ApiPublicDiscordLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roblox/check': {
      id: '/api/public/roblox/check'
      path: '/api/public/roblox/check'
      fullPath: '/api/public/roblox/check'
      preLoaderRoute: typeof ApiPublicRobloxCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roblox/join': {
      id: '/api/public/roblox/join'
      path: '/api/public/roblox/join'
      fullPath: '/api/public/roblox/join'
      preLoaderRoute: typeof ApiPublicRobloxJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicGoRoute: ApiPublicGoRoute,
  ApiPublicDiscordCallbackRoute: ApiPublicDiscordCallbackRoute,
  ApiPublicDiscordLoginRoute: ApiPublicDiscordLoginRoute,
  ApiPublicDiscordLogoutRoute: ApiPublicDiscordLogoutRoute,
  ApiPublicRobloxCheckRoute: ApiPublicRobloxCheckRoute,
  ApiPublicRobloxJoinRoute: ApiPublicRobloxJoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
